name: haskell-keycloak
version: 0.0.0.1
synopsis: "Command-line interface and library to configure Keycloak"
github: "ibizaman/haskell-keycloak"
license: BSD3
license-file: LICENSE
author: "Pierre Penninckx"
maintainer: "ibizapeanut@gmail.com"
copyright: "2020 Pierre Penninckx"
category: Keycloak

description: Please see the README on GitHub at <https://github.com/ibizaman/haskell-keycloak#readme>

dependencies:
    # base must match what comes with ghc
    - base == 4.12.0.0
    - aeson == 1.5.*
    - containers
    - generic-data == 0.7.*
    - http-api-data == 0.4.*
    - http-client == 0.6.*
    - http-client-tls == 0.3.5.*
    - http-types == 0.12.*
    - text == 1.2.*
    - time == 1.8.*
    - servant-server == 0.18.*
    - servant-client == 0.18.*
    - unordered-containers

default-extensions:
    - OverloadedStrings

library:
    source-dirs: src
    dependencies: {}

executables:
    haskell-keycloak-exe:
        main: main.hs
        source-dirs: app
        dependencies:
            - haskell-keycloak
            - aeson-pretty
            - bytestring
            - config-ini == 0.2.*
            - envy == 2.1.*
            - optparse-applicative == 0.15.*
            - optparse-generic
        ghc-options:
            - -rtsopts
            - -threaded
            - -with-rtsopts=-N

tests:
    haskell-keycloak-test:
        main: Spec.hs
        source-dirs: test
        dependencies:
            - haskell-keycloak
            - hspec == 2.7.*
            - hspec-core == 2.7.*
            - hspec-discover == 2.7.*
        ghc-options:
            - -rtsopts
            - -threaded
            - -with-rtsopts=-N

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -fwarn-incomplete-patterns
    - -fwarn-incomplete-record-updates
    - -fwarn-incomplete-uni-patterns
    - -fwarn-missing-signatures
    - -fwarn-name-shadowing
    - -fwarn-overlapping-patterns
    - -fwarn-tabs
    - -fwarn-unused-imports
