name: "build, test and package"
on:
    pull_request:
    push:
jobs:
    shell:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: cachix/install-nix-action@v12
            - uses: cachix/cachix-action@v8
              with:
                  name: ibizaman
                  authToken: "${{ secrets.CACHIX_IBIZAMAN_AUTHTOKEN }}"

            - run: nix-build shell.nix
            # TODO: make this work
            # - run: nix-shell --pure --run haskell-language-server-wrapper

    build-all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: cachix/install-nix-action@v12
            - uses: cachix/cachix-action@v8
              with:
                  name: ibizaman
                  authToken: "${{ secrets.CACHIX_IBIZAMAN_AUTHTOKEN }}"

            - run: make build-release
            - uses: actions/upload-artifact@v2
              with:
                  name: godaddy
                  path: godaddy
